package com.abc.greendaoexample.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.abc.greendaoexample.db.Location;
import com.abc.greendaoexample.db.Tag;

import com.abc.greendaoexample.db.LocationDao;
import com.abc.greendaoexample.db.TagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig tagDaoConfig;

    private final LocationDao locationDao;
    private final TagDao tagDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(Tag.class, tagDao);
    }
    
    public void clear() {
        locationDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

}
