package com.abc.greendaoexample.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCATION_TAG".
 */
public class LocationTag {

    private Long id;
    private Long location_id;
    private Long tag_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocationTag() {
    }

    public LocationTag(Long id) {
        this.id = id;
    }

    public LocationTag(Long id, Long location_id, Long tag_id) {
        this.id = id;
        this.location_id = location_id;
        this.tag_id = tag_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLocation_id() {
        return location_id;
    }

    public void setLocation_id(Long location_id) {
        this.location_id = location_id;
    }

    public Long getTag_id() {
        return tag_id;
    }

    public void setTag_id(Long tag_id) {
        this.tag_id = tag_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
